import test from 'node:test';
import assert from 'node:assert/strict';
import {createHandler as factory,automaticDate} from '../api/tratativas.js';
import {analyticsHeaders,analyticsIndexes} from '../src/utils/npsSchema.js';
const columns=[...analyticsHeaders];columns.splice(1,0,'Prazo Final');
const row=()=>columns.map(()=>'');
const response=()=>({setHeader(){},status(code){this.code=code;return this},json(body){this.body=body}});
function setup(rows=[],formula=rows){const calls=[];const handler=factory(async()=>({uid:'bko'}),async()=>'',async(url,options={})=>{calls.push({url,options});return{ok:true,json:async()=>url.includes('fields=sheets(properties)')?{sheets:[{properties:{title:'NPS',sheetId:7,gridProperties:{rowCount:1000}}}]}:url.includes(':batchUpdate')?{}:{values:url.includes('A2')?formula:[columns,...(url.includes('FORMULA')?formula:rows)]}}},async()=>columns.map((name,i)=>({name,type:i===0?'calculated':'text',options:[],strict:false})));return{handler,calls}}
test('BKO obrigatório para todas as operações',async()=>{for(const method of ['GET','POST','PATCH']){const res=response();await factory(async()=>{throw Object.assign(new Error('Restrito'),{statusCode:403})},()=>assert.fail())({method},res);assert.equal(res.code,403)}});
test('cabeçalhos repetidos, linhas vazias e versão',async()=>{const r=row();r[2]='Cliente';const {handler}=setup([r,[]]);const res=response();await handler({method:'GET'},res);assert.equal(res.code,200);assert.equal(res.body.headers.filter(h=>h==='OPERADOR RESPONSÁVEL').length,4);assert.equal(res.body.records.length,1);assert.ok(res.body.records[0].version)});
test('data exige identidade completa e nunca substitui a existente',()=>{const r=row();r[2]='Cliente';r[3]='00123';assert.equal(automaticDate(r,columns),null);r[7]='id';const stamp=automaticDate(r,columns,new Date('2026-10-08T15:30:00Z'));assert.ok(Math.abs(stamp.cell.userEnteredValue.numberValue-(46303+12.5/24))<1e-9);r[0]='07/10/2026 09:00:00';assert.equal(automaticDate(r,columns),null)});
test('cria linha e data em um batch sem executar texto como fórmula',async()=>{const values=row();values[2]='=1+1';values[3]='00123';values[7]='id';const{handler,calls}=setup();const res=response();await handler({method:'POST',body:{columns,values}},res);assert.equal(res.code,201);const writes=calls.filter(c=>c.options.method==='POST');assert.equal(writes.length,1);const req=JSON.parse(writes[0].options.body).requests;assert.equal(req[0].insertDimension.range.startIndex,1);assert.ok(req.some(r=>r.updateCells?.rows[0].values[0].userEnteredValue.stringValue==='=1+1'));assert.ok(req.some(r=>r.updateCells?.rows[0].values[0].userEnteredFormat?.numberFormat.type==='DATE_TIME'))});
test('rejeita data manual e esquema antigo',async()=>{for(const body of [{columns,values:['10/10/2026',...row().slice(1)]},{columns:[],values:row()}]){const{handler,calls}=setup();const res=response();await handler({method:'POST',body},res);assert.ok([400,409].includes(res.code));assert.equal(calls.filter(c=>c.options.method==='POST').length,0)}});
test('edição preenche data ao completar identidade',async()=>{const r=row();r[2]='Cliente';r[3]='00123';const{handler,calls}=setup([r]);const get=response();await handler({method:'GET'},get);const res=response();await handler({method:'PATCH',body:{columns,row:2,version:get.body.records[0].version,changes:[{index:7,value:'id'}]}},res);assert.equal(res.code,200);const req=JSON.parse(calls.find(c=>c.options.method==='POST').options.body).requests;assert.deepEqual(req.map(r=>r.updateCells.range.startColumnIndex),[7,0])});
test('versão antiga bloqueia gravação',async()=>{const r=row();r[2]='Cliente';const{handler,calls}=setup([r]);const res=response();await handler({method:'PATCH',body:{columns,row:2,version:'old',changes:[{index:2,value:'Outro'}]}},res);assert.equal(res.code,409);assert.equal(calls.filter(c=>c.options.method==='POST').length,0)});
test('coluna Prazo Final não desloca indicadores',()=>{const indexes=analyticsIndexes(columns);assert.equal(indexes[1],2);assert.equal(indexes[6],7);assert.equal(indexes[9],10);assert.deepEqual([14,17,20,23].map(i=>indexes[i]),[15,18,21,24])});
