import { PhoneCall, ArrowRight, CheckCircle2, Clock3 } from 'lucide-react';
const sample = { received: 6500, answered: 6450, unique: 6400, finished: 6000, eligible: 400, performed: 300, success: 200, failed: 100, pending: 100, registered: 6100 };
const number = value => value.toLocaleString('pt-BR');
const percent = (value, total) => total ? `${(value / total * 100).toLocaleString('pt-BR', { maximumFractionDigits: 2 })}%` : '—';
export default function CallbackPanel() {
  const d = sample, potential = d.finished + d.success;
  return <section className="callback-page">
    <div className="ticket-heading"><div><p className="bko-eyebrow">ACOMPANHAMENTO DA OPERAÇÃO</p><h1>Callback</h1><p>Do atendimento recebido ao retorno e registro no Foco.</p></div><span className="callback-demo">Demonstração · dados de exemplo</span></div>
    <div className="callback-notice">Primeira versão para validação. Os números abaixo são os exemplos informados e ainda não estão conectados ao CSV ou à Genesys. Os filtros dos indicadores BKO não se aplicam a esta aba.</div>
    <div className="callback-kpis">{[[PhoneCall,'Callbacks realizados',d.performed,`${percent(d.performed,d.eligible)} dos ${number(d.eligible)} elegíveis`],[CheckCircle2,'Retornos com sucesso',d.success,`${percent(d.success,d.performed)} dos realizados`],[Clock3,'Callbacks não realizados',d.pending,`${percent(d.pending,d.eligible)} dos elegíveis`],[CheckCircle2,'Registro no Foco',percent(d.registered,potential),`${number(d.registered)} de ${number(potential)} potenciais`]].map(([Icon,label,value,note])=><article className="bko-panel callback-kpi" key={label}><Icon size={19}/><p>{label}</p><strong>{typeof value==='number'?number(value):value}</strong><small>{note}</small></article>)}</div>
    <div className="callback-columns"><section className="bko-panel callback-section"><h2>Chamadas recebidas</h2><p className="callback-subtitle">Volume receptivo, separado das chamadas de retorno.</p><dl>{[['Recebidas',d.received],['Atendidas',d.answered],['Atendidas únicas',d.unique],['Finalizadas',d.finished],['Elegíveis para callback',d.eligible]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{number(value)}</dd></div>)}</dl><p className="callback-note">Elegibilidade: queda de ligação, abandono ou erro sistêmico. A identificação desses motivos na base será validada na integração.</p></section>
    <section className="bko-panel callback-section"><h2>Resultado dos retornos</h2><p className="callback-subtitle">Regra acordada: Direção = Saída identifica callback.</p><div className="callback-progress"><span>Realizados / elegíveis</span><strong>{percent(d.performed,d.eligible)}</strong><progress aria-label="Callbacks realizados sobre elegíveis" value={d.performed} max={d.eligible}/></div><dl>{[['Com sucesso',d.success,`${percent(d.success,d.performed)} dos realizados`],['Sem sucesso',d.failed,`${percent(d.failed,d.performed)} dos realizados`],['Não realizados',d.pending,`${percent(d.pending,d.eligible)} dos elegíveis`]].map(([label,value,note])=><div key={label}><dt>{label}<small>{note}</small></dt><dd>{number(value)}</dd></div>)}</dl><p className="callback-note">Com sucesso entra no potencial de registro. Sem sucesso e não realizados ficam fora desse potencial.</p></section></div>
    <section className="bko-panel callback-section callback-foco"><div><p className="bko-eyebrow">CONVERSÃO EM REGISTRO</p><h2>Potencial de registro no Foco</h2></div><div className="callback-equation"><span><strong>{number(d.finished)}</strong>Finalizadas</span><b>+</b><span><strong>{number(d.success)}</strong>Callbacks com sucesso</span><ArrowRight size={20}/><span><strong>{number(potential)}</strong>Potencial de registro</span></div><p>{number(d.registered)} registros no Foco ÷ {number(potential)} potenciais = <strong>{percent(d.registered,potential)}</strong>. Restam {number(potential-d.registered)} registros para atingir o potencial do exemplo.</p></section>
    <details className="bko-panel callback-section"><summary>Regras de contagem e próximos ajustes</summary><ul><li>Atendidas recebidas permanecem em {number(d.answered)}. Os {number(d.performed)} retornos são apresentados separadamente.</li><li>Não somar callbacks às atendidas únicas sem relacionar o retorno à chamada original.</li><li>O exemplo considera um retorno por atendimento elegível. Na integração, precisaremos separar tentativas de retorno e atendimentos únicos.</li><li>Ainda falta definir, a partir das colunas da base, como reconhecer sucesso e vincular chamadas recebidas e retornos.</li><li>Esta tela não altera regras na Genesys nem grava informações na planilha.</li></ul></details>
  </section>;
}
