import { AlertCircle, BarChart3, CheckCircle2, PhoneCall } from 'lucide-react';

const sample = { received: 6500, answered: 6450, unique: 6400, finished: 6000, eligible: 400, performed: 300, success: 200, failed: 100, pending: 100, registered: 6100 };
const number = value => Number(value).toLocaleString('pt-BR');
const percent = (value, total) => total ? `${(value / total * 100).toLocaleString('pt-BR', { maximumFractionDigits: 2 })}%` : '—';

export default function CallbackPanel() {
  const d = sample, potential = d.finished + d.success;
  const row = { received: d.received, answered: d.answered, unique: d.unique, finished: d.finished, eligible: d.eligible, performed: d.performed, success: d.success, failed: d.failed, pending: d.pending, performedRate: percent(d.performed, d.eligible), successRate: percent(d.success, d.performed), failedRate: percent(d.failed, d.performed), potential, registered: d.registered, registeredRate: percent(d.registered, potential) };
  const columns = [
    ['Recebidas', 'received', 'Volume recebido'], ['Atendidas', 'answered', 'Answered'], ['Atendidas únicas', 'unique', 'IDs distintos'], ['Finalizadas', 'finished', 'Base concluída'], ['Elegíveis para callback', 'eligible', 'Queda, abandono ou erro'], ['Callback realizado', 'performed', 'Retornos feitos'], ['Callback com sucesso', 'success', 'Entra no potencial'], ['Callback sem sucesso', 'failed', 'Fora do potencial'], ['Callback não realizado', 'pending', 'Fora do potencial'], ['% realizado', 'performedRate', 'Sobre elegíveis'], ['% com sucesso', 'successRate', 'Sobre realizados'], ['% sem sucesso', 'failedRate', 'Sobre realizados'], ['Potencial de registros', 'potential', 'Finalizadas + sucesso'], ['Registro no Foco', 'registered', 'Registros realizados'], ['% registro no Foco', 'registeredRate', 'Sobre o potencial'],
  ];
  return <section className="callback-page">
    <div className="callback-hero"><div><p className="bko-eyebrow">ACOMPANHAMENTO DA OPERAÇÃO</p><h1>Callback</h1><p>Recebimento, retorno e conversão em registro em uma única visão.</p></div><div className="callback-hero-summary"><span><PhoneCall size={16}/>Retornos realizados</span><strong>{number(d.performed)}</strong><small>{row.performedRate} dos elegíveis</small></div></div>
    <div className="callback-notice"><AlertCircle size={17}/><p><strong>Demonstração.</strong> Os números abaixo são os exemplos informados e ainda não estão conectados ao CSV ou à Genesys.</p></div>
    <section className="callback-table-card" aria-labelledby="callback-table-title"><div className="callback-table-title"><div><p className="bko-eyebrow">PAINEL CONSOLIDADO</p><h2 id="callback-table-title">Indicadores de callback</h2><p>Uma linha de acompanhamento para o período selecionado.</p></div><span><BarChart3 size={18}/>Dados de exemplo</span></div><div className="callback-table-scroll"><table className="callback-main-table"><thead><tr>{columns.map(([label, , note]) => <th key={label} scope="col"><span>{label}</span><small>{note}</small></th>)}</tr></thead><tbody><tr>{columns.map(([, key]) => <td key={key} className={key.includes('Rate') ? 'callback-rate' : ''}>{row[key]}</td>)}</tr></tbody></table></div><div className="callback-table-legend"><span><i className="callback-dot received"/>Chamadas recebidas</span><span><i className="callback-dot callback"/>Etapa de callback</span><span><i className="callback-dot focus"/>Conversão no Foco</span><p>Potencial de registros = Finalizadas + Callback com sucesso.</p></div></section>
    <div className="callback-insights"><article><span className="callback-insight-icon callback"><PhoneCall size={19}/></span><p>Eficiência do callback</p><strong>{row.performedRate}</strong><small>{number(d.performed)} realizados de {number(d.eligible)} elegíveis</small></article><article><span className="callback-insight-icon success"><CheckCircle2 size={19}/></span><p>Sucesso dos retornos</p><strong>{row.successRate}</strong><small>{number(d.success)} retornos com sucesso</small></article><article><span className="callback-insight-icon focus"><BarChart3 size={19}/></span><p>Registro no Foco</p><strong>{row.registeredRate}</strong><small>{number(d.registered)} de {number(potential)} potenciais</small></article></div>
    <details className="bko-panel callback-section"><summary>Regras de contagem e próximos ajustes</summary><ul><li>Direção Entrada/Saída ou Saída identifica callback.</li><li>Atendidas conta aceitações de chamadas distribuídas por fila (ACD). Atendidas únicas conta IDs de conversa distintos com pelo menos um atendimento ACD.</li><li>Uma transferência direta entre operadores não acrescenta Answered para o segundo operador. Transferência para outra fila, atendida por distribuição ACD, acrescenta Answered.</li><li>Com sucesso entra no potencial de registro. Sem sucesso e não realizados ficam fora dele.</li><li>Os filtros dos indicadores BKO não se aplicam a esta aba. Esta tela não grava informações na planilha.</li></ul><p className="callback-note"><a href="https://help.genesys.cloud/faqs/what-is-the-difference-between-the-answered-and-handle-metrics/" target="_blank" rel="noreferrer" className="underline">Fonte: Genesys — diferença entre Answered e Handle</a></p></details>
  </section>;
}
