import NpsDeadlines, { NpsStatusCard } from './NpsDeadlines';
import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Clock3, CheckCircle2, AlertCircle, Users, Upload, ChevronRight, SlidersHorizontal, Link2 } from 'lucide-react';
import { analyze, defaults, day, group, joinInteractions, normalize, parseInteractions } from '../utils/tratativaAnalytics';
const n=value=>Number(value).toLocaleString('pt-BR');
const pct=(a,b)=>b?`${(100*a/b).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`:'—';
const Bars=({items,empty='Sem dados para este recorte.',color=''})=>{const max=Math.max(1,...items.map(i=>i.count));return items.length?<div className={`ta-bars ${color}`}>{items.map(({label,count})=><div key={label}><div><span>{label}</span><strong>{n(count)}</strong></div><div className="ta-track"><i style={{width:`${count/max*100}%`}}/></div></div>)}</div>:<p className="ta-empty">{empty}</p>};
const Card=({title,note,children,className=''})=><section className={`ta-card ${className}`}><header><h2>{title}</h2>{note&&<p>{note}</p>}</header>{children}</section>;
const Table=({headers,children})=><div className="ticket-table-scroll"><table className="ticket-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
export default function TratativaAnalytics({ records, onOpen }) {
 const [rules,setRules]=useState({...defaults}),[draft,setDraft]=useState({...defaults}),[ruleError,setRuleError]=useState('');
 const [start,setStart]=useState(''),[end,setEnd]=useState(''),[operator,setOperator]=useState(''),[status,setStatus]=useState(''),[channel,setChannel]=useState('');
 const [source,setSource]=useState(null),[filename,setFilename]=useState(''),[fileError,setFileError]=useState(''),[reading,setReading]=useState(false),[joinFilter,setJoinFilter]=useState(''),[joinPage,setJoinPage]=useState(1),[priorityPage,setPriorityPage]=useState(1);
 const all=useMemo(()=>analyze(records,rules),[records,rules]);
 const scoped=useMemo(()=>all.rows.filter(r=>(!start||(r.start!==null&&r.start>=day(start)))&&(!end||(r.start!==null&&r.start<=day(end)))&&(!operator||r.owner===operator)&&(!status||r.values[9]===status)&&(!channel||r.values[12]===channel)),[all,start,end,operator,status,channel]);
 const a=useMemo(()=>analyze(scoped,rules),[scoped,rules]);
 useEffect(()=>{setPriorityPage(1);setJoinPage(1);},[scoped]);
 const joins=useMemo(()=>joinInteractions(a.rows,source),[a,source]);
 const matched=joins.filter(r=>r.interaction),callbacks=matched.filter(r=>r.interaction.callback);
 const joinRows=joins.filter(r=>!joinFilter||(joinFilter==='callback'?r.interaction?.callback:joinFilter==='missing'?!r.values[6]?.trim():!r.interaction&&r.values[6]?.trim()));
 const uniqueOptions=index=>[...new Set(records.map(r=>r.values[index]).filter(Boolean))].sort();
 const resetPages=()=>{setPriorityPage(1);setJoinPage(1);};
 const upload=async event=>{const file=event.target.files?.[0];if(!file)return;setReading(true);setFileError('');try{if(file.size>20*1024*1024)throw new Error('Selecione um CSV de até 20 MB.');const result=parseInteractions(await file.text());setSource(result);setFilename(file.name);setJoinPage(1);}catch(error){setFileError(error.message);}finally{setReading(false);event.target.value='';}};
 const applyRules=event=>{event.preventDefault();const split=value=>String(value).split(';').map(normalize).filter(Boolean);if(split(draft.open).some(v=>split(draft.closed).includes(v))||split(draft.success).some(v=>split(draft.failure).includes(v))){setRuleError('Um valor não pode pertencer aos dois grupos opostos.');return;}setRules({...draft,age:Math.max(1,Number(draft.age)||7)});setRuleError('');resetPages();};
 return <div className="ta-dashboard">
  <div className="ta-intro"><div><span className="ta-kicker">VISÃO OPERACIONAL</span><h2>Do primeiro contato à conclusão</h2><p>Prioridades, tentativas e resultados das tratativas em um só lugar.</p></div><div className="ta-source"><span className="ta-dot"/>Planilha conectada<strong>{n(records.length)} registros na base</strong></div></div>
  <div className="ta-filters"><label>Início da tratativa<input type="date" value={start} onChange={e=>{setStart(e.target.value);resetPages();}}/></label><label>Até<input type="date" value={end} min={start} onChange={e=>{setEnd(e.target.value);resetPages();}}/></label>{[['Responsável',operator,setOperator,all.operators.map(r=>r.label).filter(v=>v!=='Não informado')],['Status',status,setStatus,uniqueOptions(9)],['Forma de contato',channel,setChannel,uniqueOptions(12)]].map(([label,value,set,options])=><label key={label}>{label}<select value={value} onChange={e=>{set(e.target.value);resetPages();}}><option value="">Todos</option>{options.map(o=><option key={o}>{o}</option>)}</select></label>)}<button onClick={()=>{setStart('');setEnd('');setOperator('');setStatus('');setChannel('');resetPages();}}>Limpar filtros</button></div>
  {!records.length&&<div className="ta-info"><AlertCircle size={18}/><p>A planilha está vazia. A estrutura abaixo está pronta para os registros reais; nenhum número de demonstração foi incluído.</p></div>}
  {start&&end&&start>end&&<p role="alert" className="ticket-error">A data final precisa ser igual ou posterior à inicial.</p>}
  <div className="ta-metrics">{[[BarChart3,'Tratativas no recorte',n(a.rows.length),'Registros da planilha'],[Clock3,'Em aberto',n(a.open.length),`${n(a.unknown)} com status não classificado`],[CheckCircle2,'Concluídas',n(a.closed),`${pct(a.closed,a.rows.length)} do recorte`],[AlertCircle,'Precisam de atenção',n(a.priorities.length),'Abertas com sinal de prioridade'],[Clock3,'Tempo médio em aberto',a.averageAge===null?'—':`${a.averageAge.toLocaleString('pt-BR',{maximumFractionDigits:1})} dias`,`${n(a.missingDates)} abertas sem data válida`],[CheckCircle2,'Sucesso da ligação',pct(a.success,a.success+a.failure),`${a.success} sucessos / ${a.success+a.failure} resultados classificados`]].map(([Icon,label,value,note])=>label === 'Em aberto' ? <NpsStatusCard key={label} analysis={a}/> : <article className="ta-metric" key={label}><Icon size={18}/><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</div>
  <NpsDeadlines rows={a.rows} onOpen={onOpen}/>
  <details className="ta-rules"><summary><SlidersHorizontal size={16}/>Critérios da análise e classificação dos status</summary><p>Correspondência exata, ignorando maiúsculas e acentos. Confira os termos com a equipe: valores não reconhecidos ficam sem classificação. Ajustes valem apenas nesta sessão e não alteram a planilha.</p><p>Valores observados nos status de contato: {[...new Set(records.flatMap(r=>[15,18,21,24].map(i=>r.values[i])).filter(Boolean))].join('; ') || 'nenhum'}. Resultado Foco: {uniqueOptions(26).join('; ') || 'nenhum'}. Encaminhamento N2: {uniqueOptions(29).join('; ') || 'nenhum'}.</p><form onSubmit={applyRules}><div className="ta-rule-grid">{[['open','Status em aberto'],['closed','Status concluídos'],['success','Resultado com sucesso (contatos e Foco)'],['failure','Resultado sem sucesso (contatos e Foco)'],['n2','Encaminhado ao N2']].map(([key,label])=><label key={key}>{label}<input value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/><small>Separe os valores por ponto e vírgula.</small></label>)}<label>Priorizar a partir de quantos dias?<input type="number" min="1" max="3650" value={draft.age} onChange={e=>setDraft({...draft,age:e.target.value})}/></label></div>{ruleError&&<p role="alert">{ruleError}</p>}<button className="bko-primary">Aplicar critérios</button></form><ul><li>Tempo em aberto usa dias corridos desde o início, no calendário de São Paulo. Datas inválidas, futuras ou ausentes são excluídas da média.</li><li>Um contato conta como tentativa quando tem status ou detalhamento; apenas um operador atribuído não comprova tentativa.</li><li>Responsável é o último operador preenchido entre os quatro contatos. Participações por operador contam a presença em uma tratativa uma única vez.</li><li>Taxas de sucesso usam apenas resultados classificados como sucesso ou insucesso. Sem classificação aparece separado.</li><li>Não há data de conclusão na planilha: tempo até a resolução está indisponível. Data de resposta e de contato não substituem a conclusão.</li></ul></details>
  <Card title="Fila de prioridades" note={`Casos abertos há ${rules.age}+ dias, sem responsável ou com pelo menos três tentativas. Ordem: quantidade de sinais e maior tempo em aberto.`} className="ta-priority">
   {a.priorities.length?<><Table headers={['Cliente / ID Genesys','Tempo aberto','Tentativas','Responsável','Atenção','Ação']}>{a.priorities.slice((priorityPage-1)*10,priorityPage*10).map(r=><tr key={r.row}><td><strong>{r.values[1]||'Sem nome'}</strong><small>{r.values[6]||'Sem ID'}</small></td><td>{r.age===null?'Sem data válida':`${r.age} dias`}</td><td>{r.attemptCount}/4</td><td>{r.owner||'Não atribuído'}</td><td><div className="ta-tags">{r.flags.map(f=><span key={f}>{f}</span>)}</div></td><td><button className="ticket-open" onClick={()=>onOpen(r)}>Abrir<ChevronRight size={14}/></button></td></tr>)}</Table><div className="ticket-pagination"><span>{a.priorities.length} prioridades</span><div><button disabled={priorityPage===1} onClick={()=>setPriorityPage(p=>p-1)}>Anterior</button><span>{priorityPage}</span><button disabled={priorityPage*10>=a.priorities.length} onClick={()=>setPriorityPage(p=>p+1)}>Próxima</button></div></div></>:<p className="ta-empty">Nenhum caso se enquadra nos critérios neste recorte.</p>}
  </Card>
  <div className="ta-grid"><Card title="Distribuição por status" note="Valores originais da planilha, inclusive os ainda não classificados."><Bars items={a.statuses}/></Card><Card title="Tempo em aberto" note="Somente status classificados como abertos, com data de início válida."><Bars items={a.ages} color="amber"/><p className="ta-note">{a.missingDates} casos abertos fora das faixas por falta de data válida.</p></Card></div>
  <Card title="Tentativas e sucesso por contato" note="Uma tratativa pode aparecer em mais de uma tentativa. Terceiro e quarto contatos não são obrigatórios."><Table headers={['Tentativa','Registradas','Com sucesso','Sem sucesso','Sem classificação','Taxa de sucesso']}>{a.attempts.map(t=><tr key={t.number}><td><strong>{t.number}º contato</strong></td><td>{t.total}</td><td>{t.success}</td><td>{t.failure}</td><td>{t.unknown}</td><td>{pct(t.success,t.success+t.failure)}<small>sobre {t.success+t.failure} classificados</small></td></tr>)}</Table><div className="ta-attempt-summary">{group(a.rows,r=>`${r.attemptCount} tentativa${r.attemptCount===1?'':'s'}`).map(g=><span key={g.label}><strong>{g.count}</strong> {g.label}</span>)}</div></Card>
  <div className="ta-grid">{[['Resultados por forma de contato',a.channels],['Resultados por canal de conclusão',a.conclusionChannels]].map(([title,items])=><Card key={title} title={title} note="Sucesso conforme o campo SUCESSO LIGAÇÃO (FOCO); não equivale a medir resolução de todos os canais.">{items.length?<Table headers={['Canal','Tratativas','Sucesso','Taxa / classificados']}>{items.map(g=><tr key={g.label}><td>{g.label}</td><td>{g.count}</td><td>{g.success}</td><td>{pct(g.success,g.classified)}<small>{g.classified} classificados · {g.count-g.classified} sem classificação</small></td></tr>)}</Table>:<p className="ta-empty">Nenhum canal informado neste recorte.</p>}</Card>)}</div>
  <div className="ta-grid"><Card title="Distribuição por responsável" note="Último operador preenchido em cada tratativa. Não representa ranking de produtividade."><Bars items={a.operators}/></Card><Card title="Participações da equipe" note="Cada operador conta uma vez por tratativa, mesmo presente em vários contatos."><Bars items={group(a.rows.flatMap(r=>[...new Set(r.attempts.map(t=>t.operator).filter(Boolean))].map(name=>({name}))),r=>r.name)}/></Card></div>
  <div className="ta-grid"><Card title="Encaminhamentos à Ouvidoria / N2" note="Classificação pelo campo ENCAMINHAMENTO N2, conforme os critérios acima."><div className="ta-highlight"><strong>{a.n2.length}</strong><span>{pct(a.n2.length,a.rows.length)} das tratativas do recorte</span></div><Bars items={group(a.n2,r=>r.values[9])}/><details><summary>Ver os encaminhamentos</summary><div className="ta-detail-list">{a.n2.map(r=><button key={r.row} onClick={()=>onOpen(r)}>{r.values[1]||'Sem nome'} · {r.values[9]||'Sem status'}<ChevronRight size={14}/></button>)}{!a.n2.length&&<p className="ta-empty">Nenhum encaminhamento classificado.</p>}</div></details></Card><Card title="Motivos e comentários recorrentes" note="Descrições idênticas agrupadas; textos diferentes sobre o mesmo assunto não são unidos automaticamente."><Bars items={group(a.rows.filter(r=>r.values[8]?.trim()),r=>r.values[8].trim()).slice(0,8)}/><details><summary>Termos frequentes nos comentários e descrições</summary><p className="ta-note">Contagem de tratativas que mencionam cada termo. São pistas para revisão, não categorias de motivo confirmadas.</p><Bars items={a.terms}/></details></Card></div>
  <Card title="Tratativa × Callback" note="Vínculo exato entre ID Genesys da tratativa e ID de conversa do CSV. Nenhuma associação por telefone ou nome." className="ta-link-card"><div className="ta-upload"><div><Link2 size={22}/><h3>Conecte o arquivo de interações</h3><p>O CSV é processado só neste navegador. Callback: Direção = Entrada/Saída ou Saída. A importação não altera a aba Callback nem a planilha.</p></div><label className="bko-primary"><Upload size={16}/>{reading?'Lendo arquivo…':'Importar CSV'}<input className="sr-only" type="file" accept=".csv,text/csv" disabled={reading} onChange={upload}/></label></div>{fileError&&<p className="ticket-error" role="alert">{fileError}</p>}
   {source?<><div className="ta-info"><p><strong>{filename}</strong> · {source.total} linhas · {source.map.size} IDs únicos · {source.callbacks} IDs de callback · {source.duplicates} linhas repetindo ID · {source.blank} sem ID</p><button onClick={()=>{setSource(null);setFilename('');}}>Remover arquivo</button></div><div className="ta-link-stats"><span><strong>{matched.length}</strong>tratativas vinculadas</span><span><strong>{callbacks.length}</strong>vinculadas a callback</span><span><strong>{joins.filter(r=>!r.values[6]?.trim()).length}</strong>sem ID Genesys</span><span><strong>{joins.filter(r=>r.values[6]?.trim()&&!r.interaction).length}</strong>ID não localizado</span></div><p className="ta-note">Ausência de vínculo significa apenas que o ID não foi encontrado neste arquivo. Não prova ausência de callback. Várias tratativas podem compartilhar o mesmo ID; IDs de callback vinculados distintos: {new Set(callbacks.map(r=>normalize(r.values[6]))).size}.</p><label className="ta-join-filter">Exibir<select value={joinFilter} onChange={e=>{setJoinFilter(e.target.value);setJoinPage(1);}}><option value="">Todas as tratativas</option><option value="callback">Vinculadas a callback</option><option value="unmatched">ID não localizado</option><option value="missing">Sem ID Genesys</option></select></label><Table headers={['Cliente','ID Genesys','Direção no CSV','Status da tratativa','Resultado Foco','Ação']}>{joinRows.slice((joinPage-1)*20,joinPage*20).map(r=><tr key={r.row}><td>{r.values[1]||'—'}</td><td>{r.values[6]||'Sem ID'}</td><td>{r.interaction?.directions.join(', ')||'Não vinculado'}</td><td>{r.values[9]||'—'}</td><td>{r.values[26]||'Não informado'}</td><td><button className="ticket-open" onClick={()=>onOpen(r)}>Detalhes</button></td></tr>)}</Table><div className="ticket-pagination"><span>{joinRows.length} tratativas</span><div><button disabled={joinPage===1} onClick={()=>setJoinPage(p=>p-1)}>Anterior</button><span>{joinPage}</span><button disabled={joinPage*20>=joinRows.length} onClick={()=>setJoinPage(p=>p+1)}>Próxima</button></div></div></>:<p className="ta-empty">Importe um CSV para consultar os vínculos com dados reais. Sucesso continua sendo definido na tratativa, não pela direção da interação.</p>}
  </Card>
  <Card title="Qualidade dos dados" note="Pendências que limitam os indicadores."><div className="ta-quality"><span><strong>{a.unknown}</strong>Status sem classificação</span><span><strong>{a.rows.length-a.success-a.failure}</strong>Resultado Foco sem classificação</span><span><strong>{a.rows.filter(r=>!r.owner).length}</strong>Sem responsável</span><span><strong>{a.rows.filter(r=>r.age===null).length}</strong>Data inicial ausente, inválida ou futura</span></div><p className="ta-note">Tempo até a resolução: indisponível. É necessário registrar a data de conclusão para calcular esse indicador.</p></Card>
 </div>;
}
